### PR TITLE
remove guid field when creating new user

### PR DESCRIPTION
**Pull request by adammeyer**

### CODE REVIEW

**Comment by Omicron7** [comment]
Does this really remove the `guid` field or just the toLowerCase() on it?

**Comment by adammeyer** [comment]
The actual field removal was done in the web repo

**Comment by Omicron7** [comment]
This is the web repo. I see the removal in the apiUser.js, but the other changes just look like removing toLowerCase(). This is my first react review, so I may be missing something.

**Comment by adammeyer** [comment]
O sorry, I removed the toLowerCase because it won't be sent in on create anymore, but still will be on an update.  The toLowerCase was failing when undefined and isn't needed on an update since the guid is not changeable.

**Pull request merged**
